spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: skydive_forecast_user
    show-sql: true
  liquibase:
    enabled: true
    default-schema: skydive_forecast_user

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET_KEY}
