name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/skydive_forecast_user_db
      SPRING_DATASOURCE_USERNAME: skydive_forecast_user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_DATA_REDIS_HOST: localhost
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: pass

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous containers and volumes
        run: |
          docker compose down -v || true
          docker volume prune -f || true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start services with docker compose
        run: docker compose up -d postgres redis

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          timeout 120 bash -c 'until docker compose exec -T postgres pg_isready -U skydive_forecast_user; do echo "Waiting..."; sleep 3; done'
          echo "PostgreSQL is ready!"

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run tests
        run: mvn test

      - name: Generate test coverage
        run: mvn jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Stop services
        if: always()
        run: docker compose down