name: Docker Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Test docker compose
        run: |
          docker compose up -d
          echo "Waiting for services to be healthy..."
          timeout 120 bash -c 'until docker exec skydive-app curl -f http://localhost:8081/actuator/health 2>/dev/null; do sleep 5; done' || true
          docker compose logs app
          docker compose down
